routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/factors', 'FactorsController');
    Route::resource('/undertests', 'UndertestsController');
    Route::resource('/tests', 'TestsController');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Factor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Factor extends Model
{
    public $guarded = [];

    public function undertests()
    {
        return $this->belongsToMany(Undertest::class);
    }
}

app/Test.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Test extends Model
{
    protected $guarded = ['file'];


    public function undertests()
    {
        return $this->hasMany(Undertest::class);
    }

    public function addFile($file, $file_update = "")
    {
        if (!$file) return;
        if($file_update) Storage::delete($file_update);

        $filename = "test_" . $this->id . ".csv";
        $this->file = $file->storeAs('tests', $filename);
        $this->save();
    }

}

app/Undertest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Undertest extends Model
{
    public $guarded = ['factors', 'test'];

    public function factors()
    {
        return $this->belongsToMany(Factor::class);
    }

    public function test()
    {
        return $this->belongsTo(Test::class);
    }

    public function setFactors($factors_id)
    {
        $factors_id = array_diff($factors_id, array(''));
        $this->factors()->detach();
        if ($factors_id) {
            $this->factors()->attach($factors_id);
        }
    }

    public function setTest($test_id)
    {
        if ($test_id) {
            $this->test_id = $test_id;
            $this->save();
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FactorsController.php
<?php

namespace App\Http\Controllers;

use App\Factor;
use Illuminate\Http\Request;

class FactorsController extends Controller
{

    public function index()
    {
        $factors = Factor::paginate(10);
        return view('factors.index', ['factors' => $factors]);
    }

    public function create()
    {
        return view('factors.add');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'symbol' => 'required'
        ]);

        Factor::create($request->all());
        return redirect()->route('factors.index');
    }

    public function show(Factor $factor)
    {
        return redirect()->route('factors.index');
    }

    public function edit(Factor $factor)
    {
        return view('factors.edit', ['factor' => $factor]);
    }

    public function update(Request $request, Factor $factor)
    {
        $this->validate($request, [
            'name' => 'required',
            'symbol' => 'required'
        ]);

        $factor->update($request->all());
        return redirect()->route('factors.index');
    }

    public function destroy(Factor $factor)
    {
        $factor->delete();
        return redirect()->route('factors.index');
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TestsController.php
<?php

namespace App\Http\Controllers;

use App\Test;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class TestsController extends Controller
{

    public function index()
    {
        $tests = Test::all();
        return view('tests.index', compact('tests'));
    }

    public function create()
    {
        return view('tests.add');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $test = Test::create($request->all());
        $test->addFile($request->file('file'));

        return redirect()->route('tests.index');
    }

    public function edit(Test $test)
    {
        return view('tests.edit', ["test" => $test]);
    }

    public function update(Request $request, Test $test)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $test->update($request->all());
        $test->addFile($request->file('file'), $test->file);

        return redirect()->route('tests.index');
    }

    public function destroy(Test $test)
    {
        Storage::delete($test->file);
        $test->delete();
        return redirect()->route('tests.index');
    }


}

app/Http/Controllers/UndertestsController.php
<?php

namespace App\Http\Controllers;

use App\Factor;
use App\Test;
use App\Undertest;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\Resource;

class UndertestsController extends Controller
{

    public function index()
    {
        $undertests = Undertest::all();
        return view('undertests.index', ['undertests' => $undertests]);
    }

    public function create()
    {
        $factorsAll = Factor::all();
        $testAll = Test::all();
        return view('undertests.add', compact('testAll', 'factorsAll'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $undertest = Undertest::create($request->all());
        $undertest->setFactors($request->get('factors'));
        $undertest->setTest($request->get('test'));
        return redirect()->route('undertests.index');
    }

    public function show(Undertest $undertest)
    {
        return redirect()->route('undertests.index');
    }

    public function edit(Undertest $undertest)
    {
        $factorsUndertest = $undertest->factors()->orderBy('factor_undertest.id')->pluck('factor_id')->all();
        $factorsAll = Factor::all();
        $testAll = Test::all();
        return view('undertests.edit', compact('undertest', "factorsUndertest", "factorsAll", "testAll"));
    }

    public function update(Request $request, Undertest $undertest)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $undertest->update($request->all());
        $undertest->setFactors($request->get('factors'));
        $undertest->setTest($request->get('test'));
        return redirect()->route('undertests.index');
    }

    public function destroy(Undertest $undertest)
    {
        $undertest->delete();
        return redirect()->route('undertests.index');
    }

}

resources/views/errors.blade.php
@if ($errors->any())

    <div style="margin: 10px 0;" class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>

@endif

resources/views/factors/_form.blade.php
{{csrf_field()}}
<div class="box-body">
    <div class="col-md-6">
        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" class="form-control" id="name" value="{{$factor->name ?? old('name')}}" name="name">
        </div>
        <div class="form-group">
            <label for="symbol">Символ</label>
            <input type="text" class="form-control" id="symbol" value="{{$factor->symbol ?? old('symbol')}}"
                   name="symbol">
        </div>
        <input type="submit" value="Сохранить" class="btn btn-success">
    </div>
</div>

resources/views/factors/add.blade.php
@extends('layout')

@section('content')

    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Добавить фактор</h3>
                @include('errors')
            </div>

            <form action="{{route('factors.store')}}" method="post">

                @include('factors._form')
            </form>

        </div>
    </section>

@endsection

resources/views/factors/edit.blade.php
@extends('layout')

@section('content')

    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Редактировать фактор #{{$factor->id}}</h3>
                @include('errors')
            </div>

            <form action="{{route('factors.update', $factor)}}" method="post">
                <input type="hidden" name="_method" value="put">

                @include('factors._form')
            </form>

        </div>
    </section>

@endsection

resources/views/factors/index.blade.php
@extends('layout')

@section('content')

    <section class="content-header">
        <h1>Факторы</h1>
    </section>


    <section class="content">

        <div class="box">
            <div class="box-body">
                <div class="form-group">
                    <a href="{{route('factors.create')}}" class="btn btn-success">Добавить</a>
                </div>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Название</th>
                        <th>Символ</th>
                        <th width="200px"></th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($factors as $factor)
                        <tr>
                            <td><a href="{{route('factors.edit', $factor)}}">{{$factor->name}}</a></td>
                            <td>{{$factor->symbol}}</td>
                            <td>
                                <form onsubmit="if(confirm('Вы действительно хотите удалить?')){ return true }else{ return false }"
                                      action="{{route('factors.destroy', $factor)}}" method="post">
                                    <input type="hidden" name="_method" value="DELETE">
                                    {{ csrf_field() }}
                                    <div class="btn-group">
                                        <button type="submit" class="btn btn-danger">Удалить</button>
                                        <a href="{{route('factors.edit', $factor)}}" class="btn btn-warning">Редактировать</a>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>

                {{$factors->links()}}
            </div>
        </div>
    </section>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>АСИ | Report</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href='/admin/bootstrap/css/bootstrap.min.css'>
    <link rel="stylesheet" href='/admin/font-awesome/4.5.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href='/admin/ionicons/2.0.1/css/ionicons.min.css'>
    <link rel="stylesheet" href='/admin/plugins/iCheck/minimal/_all.css'>
    <link rel="stylesheet" href='/admin/plugins/datepicker/datepicker3.css'>
    <link rel="stylesheet" href='/admin/plugins/select2/select2.min.css'>
    <link rel="stylesheet" href='/admin/plugins/datatables/dataTables.bootstrap.css'>
    <link rel="stylesheet" href='/admin/dist/css/AdminLTE.min.css'>
    <link rel="stylesheet" href='/admin/dist/css/skins/_all-skins.min.css'>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>А</b>СИ</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Report </b>АСИ</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="hidden-xs">Alexander</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            @include('sidebar')
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- =============================================== -->

    <div class="content-wrapper">
        @yield('content')
    </div>

    <footer class="main-footer">
        <div class="pull-right hidden-xs">

        </div>
        <strong>АСИ Report &copy; {{date("Y")}}.</strong>
    </footer>


    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<script src='/admin/plugins/jQuery/jquery-2.2.3.min.js'></script>
<script src='/admin/bootstrap/js/bootstrap.min.js'></script>
<script src='/admin/plugins/select2/select2.full.min.js'></script>
<script src='/admin/plugins/datepicker/bootstrap-datepicker.js'></script>
<script src='/admin/plugins/datatables/jquery.dataTables.min.js'></script>
<script src='/admin/plugins/datatables/dataTables.bootstrap.min.js'></script>
<script src='/admin/plugins/slimScroll/jquery.slimscroll.min.js'></script>
<script src='/admin/plugins/fastclick/fastclick.js'></script>
<script src='/admin/plugins/iCheck/icheck.min.js'></script>
<script src='/admin/dist/js/app.min.js'></script>
<script src='/admin/dist/js/demo.js'></script>
<script src='/admin/dist/js/scripts.js'></script>
<script src="/admin/plugins/ckeditor/ckeditor.js"></script>
<script src="/admin/plugins/ckfinder/ckfinder.js"></script>
<script>
    $(document).ready(function () {
        var editor = CKEDITOR.replaceAll();
        CKFinder.setupCKEditor(editor);

        $(document).on("click", ".btn-add-elem", function (e) {
            var select = $(this).parent().find(".block-elements").html();
            $(".block-elements-add").append(select);
        });
    })

</script>

<style>
    .dataTables_info, .dataTables_paginate, .dataTables_length, .dataTables_filter {
        display: none;
    }
</style>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/sidebar.blade.php
<ul class="sidebar-menu">
    <li class="header">NAVIGATION</li>
    <li class="treeview">
        <a href="{{route('home')}}">
            <i class="fa fa-dashboard"></i> <span>Админ-панель</span>
        </a>
    </li>

    <li class="header">ТЕСТЫ</li>

    <li><a href="{{route('tests.index')}}"><i class="fa fa-bookmark"></i> <span>Тесты</span></a></li>
    <li><a href="{{route('undertests.index')}}"><i class="fa fa-bookmark"></i> <span>Подтесты</span></a></li>
    <li><a href="{{route('factors.index')}}"><i class="fa fa-flag"></i> <span>Факторы</span></a></li>

    <li class="header">СЛОВЕСНЫЕ ИНТЕРПРЕТАЦИИ</li>

    <li><a href=""><i class="fa fa-book"></i> <span>Категории</span></a></li>
    <li><a href=""><i class="fa fa-book"></i> <span>Предложения</span></a></li>

</ul>

resources/views/undertests/_form.blade.php
{{csrf_field()}}
<div class="box-body">
    <div class="col-md-6">
        <div class="form-group">
            <label for="name">Название</label>
            <input type="text" class="form-control" id="name" value="{{$undertest->name ?? old('name')}}" name="name">
        </div>
        <div class="form-group">
            <label for="name">Прикрепить к тесту</label>
            <select name="test" class="form-control">
                <option value="0">Выберите тест</option>
                @if (isset($testAll))
                    @if(isset($undertest->test))
                        @foreach($testAll as $test)
                            <option @if($undertest->test->id == $test->id){{'selected'}}@endif value="{{$test->id}}">
                                {{$test->name}}
                            </option>
                        @endforeach
                    @else
                        @foreach($testAll as $test)
                            <option value="{{$test->id}}">{{$test->name}}</option>
                        @endforeach
                    @endif
                @endif
            </select>
        </div>
    </div>
</div>

<div class="box-body">
    <div class="col-md-6">
        <div class="form-group">
            <label>Как составлять текстовое описание</label>
            <select name="type_text" class="form-control">
                <option value="0">Выберите тип</option>
                @if (isset($undertest->type_graph))
                    <option @if($undertest->type_text == 1){{'selected'}}@endif value="1">
                        На основе значений факторов
                    </option>
                    <option @if($undertest->type_text == 2){{'selected'}}@endif value="2">
                        Выбирать максимальное из всех факторов
                    </option>
                @else
                    <option value="1">На основе значений факторов</option>
                    <option value="2">Выбирать максимальное из всех факторов</option>
                @endif
            </select>
        </div>

        <div class="form-group">
            <label>Вид графика</label>
            <select name="type_graph" class="form-control">
                <option value="0">Выберите тип графика</option>
                @if (isset($undertest->type_graph))
                    <option @if($undertest->type_graph == 1){{'selected'}}@endif value="1">
                        Линейная диаграмма
                    </option>
                    <option @if($undertest->type_graph == 2){{'selected'}}@endif value="2">
                        Круговая диаграмма
                    </option>
                    <option @if($undertest->type_graph == 3){{'selected'}}@endif value="3">
                        Гистограмма
                    </option>
                @else
                    <option value="1">Линейная диаграмма</option>
                    <option value="2">Круговая диаграмма</option>
                    <option value="3">Гистограмма</option>
                @endif
            </select>
        </div>
    </div>
</div>

<div class="box-body">
    <div class="col-md-12">
        <div class="form-group">
            <label for="name">Составлять тексты по колонкам</label>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <input type="text" class="form-control" value="{{$undertest->text_x ?? old('text_x')}}" name="text_x">
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <input type="text" class="form-control" value="{{$undertest->text_y ?? old('text_y')}}" name="text_y">
        </div>
    </div>
</div>
<div class="box-body">
    <div class="col-md-12">
        <div class="form-group">
            <label for="name">Составлять график по колонкам</label>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <input type="text" class="form-control" value="{{$undertest->graph_x ?? old('graph_x')}}" name="graph_x">
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <input type="text" class="form-control" value="{{$undertest->graph_y ?? old('graph_y')}}" name="graph_y">
        </div>
    </div>
</div>
<div class="box-body">
    <div class="col-md-6">
        <div class="form-group">
            <label for="factors">Факторы</label>

            @if(isset($factorsUndertest))
                @foreach($factorsUndertest as $factorSelect)
                    <select class="form-control" name="factors[]">
                        <option value="">Удалить</option>
                        @foreach($factorsAll as $factor)
                            <option value="{{$factor->id}}"
                                    <?if($factor->id == $factorSelect):?>selected<?endif?>>
                                {{$factor->name}} ({{$factor->symbol}})
                            </option>
                        @endforeach
                    </select>
                @endforeach
            @endif

            <div class="block-elements">
                <select class="form-control" name="factors[]">
                    <option value="">Выберите новый фактор</option>
                    @foreach($factorsAll as $factor)
                        <option value="{{$factor->id}}">
                            {{$factor->name}} ({{$factor->symbol}})
                        </option>
                    @endforeach
                </select>
            </div>
            <div class="block-elements-add"></div>

            <button type="button" class="btn btn-block btn-default btn-add-elem">Добавить фактор
            </button>
        </div>
        <input type="submit" value="Сохранить" class="btn btn-success">
    </div>
</div>

resources/views/undertests/add.blade.php
@extends('layout')

@section('content')

    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Добавить подтест</h3>
                @include('errors')
            </div>

            <form action="{{route('undertests.store')}}" method="post">

                @include('undertests._form')
            </form>

        </div>
    </section>

@endsection

resources/views/undertests/edit.blade.php
@extends('layout')

@section('content')

    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Редактировать подтест #{{$undertest->id}}</h3>
                @include('errors')
            </div>

            <form action="{{route('undertests.update', $undertest)}}" method="post">
                <input type="hidden" name="_method" value="put">

                @include('undertests._form')
            </form>

        </div>
    </section>

@endsection

resources/views/undertests/index.blade.php
@extends('layout')

@section('content')

    <section class="content-header">
        <h1>Подтесты</h1>
    </section>


    <section class="content">

        <div class="box">
            <div class="box-body">
                <div class="form-group">
                    <a href="{{route('undertests.create')}}" class="btn btn-success">Добавить</a>
                </div>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название</th>
                        <th>Символы</th>
                        <th width="200px"></th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($undertests as $undertest)
                        <tr>
                            <td>{{$undertest->id}}</td>
                            <td><a href="{{route('undertests.edit', $undertest)}}">{{$undertest->name}}</a></td>
                            <td>{{implode(", ",$undertest->factors()->orderBy('factor_undertest.id')->pluck('symbol')->all())}}</td>
                            <td>
                                <form onsubmit="if(confirm('Вы действительно хотите удалить?')){ return true }else{ return false }"
                                      action="{{route('undertests.destroy', $undertest)}}" method="post">
                                    <input type="hidden" name="_method" value="DELETE">
                                    {{ csrf_field() }}
                                    <div class="btn-group">
                                        <button type="submit" class="btn btn-danger">Удалить</button>
                                        <a href="{{route('undertests.edit', $undertest)}}" class="btn btn-warning">Редактировать</a>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </section>

@endsection